kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-data
  annotations:
    volume.beta.kubernetes.io/storage-class: gke
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi